In [1]:
#importacion de libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction import FeatureHasher

import warnings
warnings.filterwarnings('ignore')

In [2]:
#carga de datasets
#Le especifico el tipo a algunas columnas porque sino me tira un warning, podria especificar el verdadero tipo tambien
todoSet = pd.read_csv("events_up_to_01062018.csv",\
                   dtype = {3: object,5: object,
                    6: object,7: object,
                    8: object,9: object,
                    10: object,11: object,
                    12: object,13: object,
                    14: object,15: object,
                    16: object,17: object,
                    18: object,19: object,
                    20: object,21: object,
                    22: object})
usersJunioSet = pd.read_csv("trocafone_kaggle_test.csv")

In [3]:
usersJunioSet.head()

     person
0  4886f805
1  0297fc1e
2  2d681dd8
3  cccea85e
4  4c8a8b93

In [4]:
todoSet[todoSet['person']=='40bf23ab']

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
2341644,2018-05-30 12:22:07,lead,40bf23ab,NaN,NaN,iPhone 6S,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Merge
usersTest = todoSet[todoSet['person'].isin(usersJunioSet['person'])]

In [6]:
usersTest['timestamp'] = pd.to_datetime(usersTest['timestamp'])
#Creo una columna con solo fecha sin tiempo
usersTest['fecha'] = usersTest['timestamp'].dt.date

In [7]:
def change_column_order(df, col_name, index):
    cols = df.columns.tolist()
    cols.remove(col_name)
    cols.insert(index, col_name)
    return df[cols]

# FEATURES CATEGORICOS

In [8]:
#conversion de Object a datetime
todoSet['timestamp'] = pd.to_datetime(todoSet['timestamp'])
usersTest['fecha'] = pd.to_datetime(usersTest['fecha'])
usersTest['meses'] = usersTest['timestamp'].dt.month

In [9]:
usersTest['fecha'].head()

0   2018-05-18
2   2018-05-18
3   2018-05-18
4   2018-05-18
5   2018-05-18
Name: fecha, dtype: datetime64[ns]

In [10]:
usersTest['person'].nunique()

19415

In [11]:
#GENERO FEATURE SEPARADOS POR MES

def acomodar_dataframe(dataframe):
    dataframe=dataframe.pivot_table(index='person',columns='meses').reset_index()
    #dataframe.replace([np.inf, -np.inf], 0,inplace=True)
    dataframe.fillna(0, inplace=True)
    columns = dataframe.columns.tolist()
    columns_name=[]
    for x in columns:
        columns_name=columns_name+[str(x[0])+'-'+str(x[1])]
    columns_name[0]='person'
    #columns_name[1]='label'
    dataframe.columns=columns_name
    dataframe.columns = dataframe.columns.str.replace('-1', "-Enero")
    dataframe.columns = dataframe.columns.str.replace('-2', "-Febrero")
    dataframe.columns = dataframe.columns.str.replace('-3', "-Marzo")
    dataframe.columns = dataframe.columns.str.replace('-4', "-Abril")
    dataframe.columns = dataframe.columns.str.replace('-5', "-Mayo")
#DROPEANDO COLUMNAS NULAS
    #    dataframe= dataframe.loc[:, (dataframe != 0).any(axis=0)]
    return dataframe

In [12]:
def armar_feature2(feature,nombre_columna,numero_de_columnas):
    
    #GENERO PARAMETRO FEATURE HASHING
    col=[]
    columna=nombre_columna
    cant_elem=numero_de_columnas
    #GENERO NOMBRE DE LAS COLUMNAS
    for x in range(1,cant_elem+1):
        col.append("F13_"+columna+"_fh"+str(x))
    #APLICO FEATURE HASHING Y CONCATENO
    fh = FeatureHasher(n_features=cant_elem, input_type='string')
    sp = fh.fit_transform(feature[columna])
    sp=sp.toarray().astype('int8')
    df = pd.DataFrame(sp, columns=col)
    df.reset_index(drop=True, inplace=True)
    feature.reset_index(drop=True, inplace=True)
    #TODA LA DATA JUNTA
    feature=pd.concat([feature, df], axis=1)    
    
    return [feature,cant_elem]

In [13]:
#RECUPERO Y REARMO EL DICCIONARIO

data_ref=pd.read_csv('dict_with_feature_and_number_of_columns.csv')
data_ref=data_ref[['feature','columns']]
data_ref=data_ref.set_index('feature')
data_ref=data_ref.to_dict()['columns']

data_ref

{'usersCampaignSource': 24L,
 'usersCity': 1855L,
 'usersColors': 64L,
 'usersColorsCheckouts': 52L,
 'usersColorsConversions': 35L,
 'usersConditionCheckouts': 6L,
 'usersConditionConversions': 6L,
 'usersConditionViewed': 6L,
 'usersCountry': 40L,
 'usersDevicesTypes': 5L,
 'usersModelosVistos': 194L,
 'usersModelsCheckouts': 169L,
 'usersModelsConversions': 138L,
 'usersRegionAccess': 85L,
 'usersScreenResolution': 286L,
 'usersSearchTerms': 80L,
 'usersSkusViewedBrandListing': 137L,
 'usersSkusViewedHomePage': 58L,
 'usersSkusViewedInSearchedProducts': 111L,
 'usersStorageConversion': 9L}

In [14]:
usersTest

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version,fecha,meses
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
5,2018-05-18 00:44:27,searched products,4c8a8b93,NaN,NaN,NaN,NaN,NaN,NaN,"10240,9987,10322,10085,9944,9931,13404,10154,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
7,2018-05-18 00:44:02,viewed product,29ebb414,NaN,2845.0,iPhone 6 Plus,Bom,128GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
11,2018-05-18 00:41:00,viewed product,3dc1950f,NaN,10407.0,Motorola Moto G4 Plus,Muito Bom,32GB,Preto Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
12,2018-05-18 00:40:26,viewed product,3dc1950f,NaN,3983.0,iPad Air Wi-Fi,Bom,16GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
13,2018-05-18 00:40:14,viewed product,3dc1950f,NaN,3983.0,iPad Air Wi-Fi,Bom,16GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
15,2018-05-18 00:37:51,viewed product,8ea4c165,NaN,3347.0,Samsung Galaxy S6 Flat,Bom,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
16,2018-05-18 00:37:49,viewed product,8ea4c165,NaN,3348.0,Samsung Galaxy S6 Flat,Muito Bom,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
18,2018-05-18 00:37:16,searched products,29ebb414,NaN,NaN,NaN,NaN,NaN,NaN,"3371,6357,6371,3191,2718,6001,2777,6248,2725,8...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
19,2018-05-18 00:36:52,viewed product,d8cfe234,NaN,382.0,Samsung Galaxy S5,Excelente,16GB,Preto,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
20,2018-05-18 00:36:16,ad campaign hit,29ebb414,/,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
23,2018-05-18 00:36:03,viewed product,d6bc64df,NaN,8260.0,iPhone SE,Muito Bom,64GB,Ouro Rosa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
25,2018-05-18 00:35:41,staticpage,ec9c4059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
26,2018-05-18 00:35:33,viewed product,d8cfe234,NaN,8442.0,Samsung Galaxy S7,Muito Bom,32GB,Preto,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
27,2018-05-18 00:35:24,viewed product,d8cfe234,NaN,8498.0,Samsung Galaxy S7,Muito Bom,32GB,Rosa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
32,2018-05-18 00:29:38,viewed product,d21b8e6b,NaN,7616.0,Motorola Moto G3 4G,Muito Bom,16GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
34,2018-05-18 00:29:15,ad campaign hit,2a724d87,/,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
35,2018-05-18 00:28:57,searched products,d21b8e6b,NaN,NaN,NaN,NaN,NaN,NaN,"5016,5088,8397,8429,10728,5075,7631,9216,4969,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
37,2018-05-18 00:28:27,viewed product,d8cfe234,NaN,3348.0,Samsung Galaxy S6 Flat,Muito Bom,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
39,2018-05-18 00:28:14,searched products,d21b8e6b,NaN,NaN,NaN,NaN,NaN,NaN,"12520,12507,12548,12534",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
40,2018-05-18 00:27:41,viewed product,4c8a8b93,NaN,8176.0,iPhone SE,Muito Bom,16GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
41,2018-05-18 00:27:30,ad campaign hit,4c8a8b93,/comprar/iphone/iphone-5s,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
44,2018-05-18 00:25:42,viewed product,686c49c9,NaN,10086.0,iPhone 7,Excelente,128GB,Ouro Rosa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
45,2018-05-18 00:25:27,viewed product,686c49c9,NaN,9946.0,iPhone 7,Excelente,128GB,Preto Matte,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
49,2018-05-18 00:24:21,viewed product,a08d42ea,NaN,10728.0,Motorola Moto G3 HDTV,Bom,16GB,Preto Verde,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
50,2018-05-18 00:24:16,viewed product,a08d42ea,NaN,10730.0,Motorola Moto G3 HDTV,Excelente,16GB,Preto Verde,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
63,2018-05-18 00:22:09,viewed product,c98f5cf1,NaN,3336.0,Samsung Galaxy S6 Edge,Muito Bom,64GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-18,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2341628,2018-05-30 00:22:06,lead,d9777589,NaN,NaN,Samsung Galaxy J5 PRO,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341629,2018-05-29 20:18:05,lead,70a73575,NaN,NaN,Samsung Galaxy Tab E 7 Wi-Fi + 3G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-29,5
2341633,2018-05-30 07:25:29,lead,152312a5,NaN,NaN,LG K10 Novo,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341634,2018-05-30 01:07:56,lead,a0b57323,NaN,NaN,Motorola Moto Z2 Play,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341635,2018-05-30 08:18:38,lead,125d4a36,NaN,NaN,iPhone 8 Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341636,2018-05-30 08:19:01,lead,125d4a36,NaN,NaN,iPhone 8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341637,2018-05-30 09:13:45,lead,125d4a36,NaN,NaN,iPhone 8 Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341638,2018-05-30 09:13:52,lead,125d4a36,NaN,NaN,iPhone 8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341639,2018-05-30 09:34:47,lead,b7587dca,NaN,NaN,iPhone 8 Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341640,2018-05-30 09:34:57,lead,b7587dca,NaN,NaN,iPhone 8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341641,2018-05-30 11:19:47,lead,33cd50e3,NaN,NaN,LG K10 Novo,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341644,2018-05-30 12:22:07,lead,40bf23ab,NaN,NaN,iPhone 6S,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341648,2018-05-30 14:05:12,lead,152312a5,NaN,NaN,LG K10 Novo,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341650,2018-05-30 07:18:19,lead,ff9fc164,NaN,NaN,Samsung Galaxy On 7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341651,2018-05-30 12:00:08,lead,a0b57323,NaN,NaN,Motorola Moto Z2 Play,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341652,2018-05-26 12:00:02,lead,a7ffa917,NaN,NaN,Samsung Galaxy S5 Mini,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-26,5
2341653,2018-05-29 20:36:57,lead,5538ce7e,NaN,NaN,iPad Mini Wi-Fi + 4G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-29,5
2341654,2018-05-30 15:00:57,lead,73b5ddeb,NaN,NaN,iPhone 6S Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341655,2018-05-30 16:08:47,lead,134cc999,NaN,NaN,iPhone 7 Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341656,2018-05-30 15:25:16,lead,5059f7fd,NaN,NaN,Samsung Gear Fit 2 Grande,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341657,2018-05-30 17:34:40,lead,80aea0a0,NaN,NaN,Sony Xperia Z3 Compact,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341659,2018-05-30 17:56:03,lead,866f1c41,NaN,NaN,LG K10 Novo,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-30,5
2341665,2018-05-31 12:43:38,lead,28428c64,NaN,NaN,LG K10 TV,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341666,2018-05-31 13:21:11,lead,28428c64,NaN,NaN,LG X Screen,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341669,2018-05-31 17:26:12,lead,7f199c11,NaN,NaN,LG K10 TV,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341672,2018-05-31 19:34:12,lead,7bd89bdf,NaN,NaN,LG K10 TV,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341674,2018-05-31 23:50:44,lead,73b5ddeb,NaN,NaN,iPhone 6S Plus,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341677,2018-05-31 14:49:59,lead,27b90284,NaN,NaN,Asus Zenfone 3 Max 16 GB,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341678,2018-05-31 15:21:09,lead,a0b57323,NaN,NaN,Motorola Moto Z2 Play,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5
2341679,2018-05-31 10:34:49,lead,ff9fc164,NaN,NaN,Samsung Galaxy On 7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-05-31,5

In [15]:
#13mo feature: colores vistos por el usuario por dia
usersColors = usersTest[usersTest['event'] == 'viewed product']\
              [['fecha','meses','person','color']].drop_duplicates()

usersColors=armar_feature2(usersColors,'color',data_ref['usersColors'])
usersColors=acomodar_dataframe(usersColors[0])
usersColors.shape

(18560, 321)

In [16]:
#14mo feature: colores comprados por el usuario por dia
usersColorsConversions = usersTest[usersTest['event'] == 'conversion']\
                         [['fecha','meses','person','color']].drop_duplicates()

usersColorsConversions=armar_feature2(usersColorsConversions,'color',data_ref['usersColorsConversions'])
usersColorsConversions=acomodar_dataframe(usersColorsConversions[0])
usersColorsConversions.shape

(2129, 176)

In [17]:
#15mo feature: colores que llegan al checkout por usuario por dia
usersColorsCheckouts = usersTest[usersTest['event'] == 'checkout']\
                         [['fecha','meses','person','color']].drop_duplicates()

usersColorsCheckouts=armar_feature2(usersColorsCheckouts,'color',data_ref['usersColorsCheckouts'])
usersColorsCheckouts=acomodar_dataframe(usersColorsCheckouts[0])
usersColorsCheckouts.shape

(16381, 261)

In [18]:
#16mo feature: condition de modelos con checkouts por usuario por dia
usersConditionCheckouts = usersTest[usersTest['event'] == 'checkout']\
                         [['fecha','meses','person','condition']].drop_duplicates()

usersConditionCheckouts=armar_feature2(usersConditionCheckouts,'condition',data_ref['usersConditionCheckouts'])
usersConditionCheckouts=acomodar_dataframe(usersConditionCheckouts[0])
usersConditionCheckouts.shape

(16381, 31)

In [19]:
#17mo feature: condition de modelos con conversiones por usuario por dia
usersConditionConversions = usersTest[usersTest['event'] == 'conversion']\
                         [['fecha','meses','person','condition']].drop_duplicates()

usersConditionConversions=armar_feature2(usersConditionConversions,'condition',data_ref['usersConditionConversions'])
usersConditionConversions=acomodar_dataframe(usersConditionConversions[0])
usersConditionConversions.shape

(2129, 31)

In [20]:
#18mo feature: condition de modelos vistos por usuario por dia
usersConditionViewed = usersTest[usersTest['event'] == 'viewed product']\
                         [['fecha','meses','person','condition']].drop_duplicates()

usersConditionViewed=armar_feature2(usersConditionViewed,'condition',data_ref['usersConditionViewed'])
usersConditionViewed=acomodar_dataframe(usersConditionViewed[0])
usersConditionViewed.shape

(18560, 31)

In [21]:
#19mo feature: modelo visto por usuario por dia 
usersModelosVistos = usersTest[usersTest['event'] == 'viewed product']\
                         [['fecha','meses','person','model']].drop_duplicates()

usersModelosVistos=armar_feature2(usersModelosVistos,'model',data_ref['usersModelosVistos'])
usersModelosVistos=acomodar_dataframe(usersModelosVistos[0])
usersModelosVistos.shape

(18560, 971)

In [22]:
#20mo feature: modelo con checkouts por usuario por dia
usersModelsCheckouts = usersTest[usersTest['event'] == 'checkout']\
                         [['fecha','meses','person','model']].drop_duplicates()

usersModelsCheckouts=armar_feature2(usersModelsCheckouts,'model',data_ref['usersModelsCheckouts'])
usersModelsCheckouts=acomodar_dataframe(usersModelsCheckouts[0])
usersModelsCheckouts.shape

(16381, 846)

In [23]:
#21mo feature: modelo con conversiones por usuario por dia
usersModelsConversions = usersTest[usersTest['event'] == 'conversion']\
                         [['fecha','meses','person','model']].drop_duplicates()

usersModelsConversions=armar_feature2(usersModelsConversions,'model',data_ref['usersModelsConversions'])
usersModelsConversions=acomodar_dataframe(usersModelsConversions[0])
usersModelsConversions.shape

(2129, 691)

In [24]:
#22mo feature: skus vistos en cierta busqueda en el site por usuario por dia
usersSkusViewedInSearchedProducts = usersTest[usersTest['event'] == 'searched products']\
                 [['fecha','meses','person','skus']].dropna().drop_duplicates()

usersSkusViewedInSearchedProducts=armar_feature2(usersSkusViewedInSearchedProducts,'skus',data_ref['usersSkusViewedInSearchedProducts'])
usersSkusViewedInSearchedProducts=acomodar_dataframe(usersSkusViewedInSearchedProducts[0])
usersSkusViewedInSearchedProducts.shape

(5850, 556)

In [25]:
#23mo feature: skus vistos en la home page por user por dia
usersSkusViewedHomePage = usersTest[usersTest['event'] == 'generic listing']\
                 [['fecha','meses','person','skus']].dropna().drop_duplicates()

usersSkusViewedHomePage=armar_feature2(usersSkusViewedHomePage,'skus',data_ref['usersSkusViewedHomePage'])
usersSkusViewedHomePage=acomodar_dataframe(usersSkusViewedHomePage[0])
usersSkusViewedHomePage.shape

(12578, 291)

In [26]:
#24mo feature: skus vistos en un listado especifico de una marca por user por dia
usersSkusViewedBrandListing = usersTest[usersTest['event'] == 'brand listing']\
                              [['fecha','meses','person','skus']].dropna().drop_duplicates()


usersSkusViewedBrandListing=armar_feature2(usersSkusViewedBrandListing,'skus',data_ref['usersSkusViewedBrandListing'])
usersSkusViewedBrandListing=acomodar_dataframe(usersSkusViewedBrandListing[0])
usersSkusViewedBrandListing.shape

(9621, 686)

In [27]:
#25mo feature: search terms por usuario por dia
usersSearchTerms = usersTest[usersTest['event'] == 'searched products']\
                 [['fecha','meses','person','search_term']].dropna().drop_duplicates()

usersSearchTerms=armar_feature2(usersSearchTerms,'search_term',data_ref['usersSearchTerms'])
usersSearchTerms=acomodar_dataframe(usersSearchTerms[0])
usersSearchTerms.shape

(6297, 401)

In [28]:
#26mo feature: screen resolution por usuario por dia 
usersScreenResolution = usersTest[usersTest['event'] == 'visited site']\
                 [['fecha','meses','person','screen_resolution']].dropna().drop_duplicates()

usersScreenResolution=armar_feature2(usersScreenResolution,'screen_resolution',data_ref['usersScreenResolution'])
usersScreenResolution=acomodar_dataframe(usersScreenResolution[0])
usersScreenResolution.shape

(19115, 1431)

In [29]:
#27mo feature: storage de dispositivos convertidos por usuario por dia
usersStorageConversion = usersTest[usersTest['event'] == 'conversion']\
                 [['fecha','meses','person','storage']].dropna().drop_duplicates()

usersStorageConversion=armar_feature2(usersStorageConversion,'storage',data_ref['usersStorageConversion'])
usersStorageConversion=acomodar_dataframe(usersStorageConversion[0])
usersStorageConversion.shape

(2129, 46)

In [30]:
#28mo feature: campaign source por user por dia
usersCampaignSource =  usersTest[usersTest['event'] == 'ad campaign hit']\
                 [['fecha','meses','person','campaign_source']].dropna().drop_duplicates()

usersCampaignSource=armar_feature2(usersCampaignSource,'campaign_source',data_ref['usersCampaignSource'])
usersCampaignSource=acomodar_dataframe(usersCampaignSource[0])
usersCampaignSource.shape

(16003, 121)

In [31]:
#29mo feature: country access user
usersCountry = usersTest[usersTest['event'] == 'visited site']\
                 [['fecha','meses','person','country']].dropna().drop_duplicates()

usersCountry=armar_feature2(usersCountry,'country',data_ref['usersCountry'])
usersCountry=acomodar_dataframe(usersCountry[0])
usersCountry.shape

(19116, 201)

In [32]:
#30mo feature: city access user
usersCity = usersTest[usersTest['event'] == 'visited site']\
                 [['fecha','meses','person','city']].dropna().drop_duplicates()

usersCity=armar_feature2(usersCity,'city',data_ref['usersCity'])
usersCity=acomodar_dataframe(usersCity[0])
usersCity.shape

(19116, 9276)

In [33]:
#31mo feature: region access user
usersRegionAccess = usersTest[usersTest['event'] == 'visited site']\
                 [['fecha','meses','person','region']].dropna().drop_duplicates()


usersRegionAccess=armar_feature2(usersRegionAccess,'region',data_ref['usersRegionAccess'])
usersRegionAccess=acomodar_dataframe(usersRegionAccess[0])
usersRegionAccess.shape

(19116, 426)

In [34]:
#32mo feature: device type visited site users
usersDevicesTypes = usersTest[usersTest['event'] == 'visited site']\
                 [['fecha','meses','person','device_type']].dropna().drop_duplicates()

usersDevicesTypes=armar_feature2(usersDevicesTypes,'device_type',data_ref['usersDevicesTypes'])
usersDevicesTypes=acomodar_dataframe(usersDevicesTypes[0])
usersDevicesTypes.shape#['person'].nunique()

(19116, 26)

### COMENZAMOS CON EL JOIN DE LOS FEATURES CATEGORICOS
### PRIMERO GENERAMOS EL DF DONDE REALIZAREMOS EL MERGE

In [35]:
join_features_categoricos=usersTest.loc[:,['person']].drop_duplicates()
join_features_categoricos.head()

     person
0  4886f805
2  0297fc1e
3  2d681dd8
4  cccea85e
5  4c8a8b93

In [36]:
join_features_categoricos.shape

(19415, 1)

In [37]:
#GENERO UNA LISTA DE DF PARA REALIZAR EL MERGE
features_categoricos=[usersColors,usersColorsConversions,usersColorsCheckouts,usersConditionCheckouts,usersConditionConversions,usersConditionViewed,usersModelosVistos,usersModelsCheckouts,usersModelsConversions,usersSkusViewedInSearchedProducts,usersSkusViewedHomePage,usersSkusViewedBrandListing,usersSearchTerms,usersScreenResolution,usersStorageConversion,usersCampaignSource,usersCountry,usersCity,usersRegionAccess,usersDevicesTypes]
print ("Cantidad de features categoricos",len(features_categoricos))#32-13+1=20

('Cantidad de features categoricos', 20)

In [38]:
#HAGO EL MERGE CON EL DF CREADO CON PERSON Y LABEL
for feature_to_merge in features_categoricos:
    join_features_categoricos=pd.merge(join_features_categoricos,feature_to_merge, on=['person'],how='left')

In [39]:
#QUITO LOS NA Y COLOCO 0 Y RENOMBRO LAS COLUMNAS Y GUARDO EL ARCHIVO
print join_features_categoricos.shape
join_features_categoricos=join_features_categoricos.fillna(0)
join_features_categoricos.columns = list (join_features_categoricos.columns.str.replace('_x',''))
join_features_categoricos.columns = list (join_features_categoricos.columns.str.replace('_y',''))
join_features_categoricos.to_csv('join_features_categoricos_test_final.csv')
join_features_categoricos.head()

(19415, 16801)

,person,F13_color_fh1-Enero,F13_color_fh1-Febrero,F13_color_fh1-Marzo,F13_color_fh1-Abril,F13_color_fh1-Mayo,F13_color_fh10-Enero,F13_color_fh10-Febrero,F13_color_fh10-Marzo,F13_color_fh10-Abril,...,F13_device_type_fh4-Enero,F13_device_type_fh4-Febrero,F13_device_type_fh4-Marzo,F13_device_type_fh4-Abril,F13_device_type_fh4-Mayo,F13_device_type_fh5-Enero,F13_device_type_fh5-Febrero,F13_device_type_fh5-Marzo,F13_device_type_fh5-Abril,F13_device_type_fh5-Mayo
0,4886f805,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0
1,0297fc1e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,2d681dd8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,cccea85e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,4c8a8b93,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0